### ISSUE TITLE
files in git

### ISSUE THREAD

**Issue by ensonic** [pokitto/PokittoSim#15]
any reason those are checked in? Those aren't source and it would be nice to keep the source tree clean.

	modified:   POKITTO_SIM/Pokitto_sim.depend
	modified:   POKITTO_SIM/Pokitto_sim.layout
	modified:   POKITTO_SIM/bin/Debug/Pokitto_sim
	modified:   POKITTO_SIM/main.map

**Comment by haviital** [comment]
Propaböy those could be removed

**Comment by HomineLudens** [comment]
was going to ask the same. 
Also it seems to be a orphan reference to bmp2pok in TOOLS:
`Submodule repository 'TOOLS/bmp2pok' not found.`

**Comment by pokitto** [comment]
Yep should be removed

**Comment by pokitto** [comment]
And need to fix that bmp2pok as well

**Comment by pokitto** [comment]
Unnecessary files removed, bmp2pok linked as submodule
