### ISSUE TITLE
minor read addition

### ISSUE THREAD

**Issue by lauri-piikivi** [pokitto/PokittoSim#23]
very minor step addition to the readme, for us less familiar with the IDEs and C and stuff. Amazing work!

# Pokitto Simulator early community version

author:   Jonne Valola <jonne@pokitto.com>
lisense:  BSD License

## Instructions

1. Install Code::Blocks (www.codeblocks.org) - Windows users please install the
   mingw version
2. Open Code::Blocks
3. Open project file Pok_sim.cbp from folder POKITTO_SIM
4. Select target in Menu: Build --> Select Target. You need to select *_win if you are running on windows and *_lin for linux 
5. Compile and run, play around and enjoy

If you prefer the commandline, you can also build like this:
```
codeblocks --target=HelloWorld_lin --rebuild ./POKITTO_SIM/Pokitto_sim.cbp
```

**Comment by pokitto** [comment]
Thanks!
